const API_URL = "https://telegram-api.zhen.lat";
module.exports = {
  apps: [
    {
      name: "singsing",
      script: "npm",
      args: "run singsing",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 200,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/singsing/error.log",
      out_file: "./logs/singsing/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "cowtopia",
      script: "npm",
      args: "run cowtopia",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 201,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/cowtopia/error.log",
      out_file: "./logs/cowtopia/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "blum",
      script: "npm",
      args: "run blum",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 202,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/blum/error.log",
      out_file: "./logs/blum/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "nomis",
      script: "npm",
      args: "run nomis",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 203,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/nomis/error.log",
      out_file: "./logs/nomis/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "piggy",
      script: "npm",
      args: "run piggy",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 204,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/piggy/error.log",
      out_file: "./logs/piggy/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "banana",
      script: "npm",
      args: "run banana",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 205,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/banana/error.log",
      out_file: "./logs/banana/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "gumart",
      script: "npm",
      args: "run gumart",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 206,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/gumart/error.log",
      out_file: "./logs/gumart/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "tabizoo",
      script: "npm",
      args: "run tabizoo",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 207,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/tabizoo/error.log",
      out_file: "./logs/tabizoo/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
    {
      name: "popp",
      script: "npm",
      args: "run popp",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 208,
        API_URL: API_URL,
      },
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/popp/error.log",
      out_file: "./logs/popp/out.log",
      merge_logs: true,
      max_restarts: 10,
      min_uptime: "200s",
    },
  ],
};
